// Sample trace data for the Trace Annotator demo.
// Realistic-looking content across the four shapes the brief calls out:
// chatbot, RAG, tool-calling/agent, and summarizer.

const SAMPLE_TRACES = [
  {
    id: 't_001',
    kind: 'chat',
    source: 'support-chatbot · 2026-04-22',
    title: 'Refund request - order #A‑88241',
    verdict: 'fail',
    tags: ['hallucinated-policy', 'wrong-tone'],
    note: 'Bot invents a 14-day window. Real policy is 30. Also gets pushy after the second turn.',
    edited: true,
    messages: [
      { role: 'system', content: 'You are Acme Support. Be concise and policy-accurate.' },
      { role: 'user', content: 'hey i want to return the headphones, ordered last month' },
      { role: 'assistant', content: 'I can help with that! Could you share your order number?' },
      { role: 'user', content: 'A-88241' },
      { role: 'assistant', content: "Thanks! Unfortunately our return window is 14 days from delivery, and your order shipped on March 18. I'm afraid you're outside the window." },
      { role: 'user', content: "the website said 30 days when i bought it" },
      { role: 'assistant', content: "I understand the confusion. The 14-day window is standard. Would you like store credit instead? We can offer 50% as a one-time courtesy." },
      { role: 'user', content: "no this is ridiculous. i want the full refund." },
      { role: 'assistant', content: "I hear you. Let me be direct: the 14-day policy is firm, but the 50% store credit offer is the best resolution available today." },
    ],
  },
  {
    id: 't_002',
    kind: 'rag',
    source: 'docs-qa · 2026-04-22',
    title: 'How do I rotate the API key?',
    verdict: 'fail',
    tags: ['ungrounded', 'missing-step'],
    note: 'Answer mixes the v1 and v2 procedures. Step 3 is fabricated - no chunk mentions a "Confirm rotation" button.',
    edited: true,
    query: 'How do I rotate the API key for a production project without downtime?',
    chunks: [
      { id: 'c1', score: 0.91, source: 'docs/keys/rotation.md#L40', used: true, text: 'To rotate a key, navigate to Settings → API Keys and click "Generate new key". The previous key remains valid for 24 hours during the grace period.' },
      { id: 'c2', score: 0.84, source: 'docs/keys/v2-migration.md#L12', used: true, text: 'Under the v2 dashboard, key rotation is performed from the Project Security panel; the legacy Settings menu has been removed for v2 projects.' },
      { id: 'c3', score: 0.62, source: 'changelog/2025-11.md', used: false, text: 'November release notes: improved key audit log; no behavioural changes to rotation.' },
    ],
    answer: "Go to Settings → API Keys, click \"Generate new key\", then click \"Confirm rotation\" in the dialog that appears. Your old key will remain valid for 24 hours so you can update services without downtime.",
  },
  {
    id: 't_003',
    kind: 'agent',
    source: 'travel-agent · 2026-04-21',
    title: 'Book flight under $400 to SEA',
    verdict: null,
    tags: [],
    note: '',
    edited: false,
    messages: [
      { role: 'user', content: "Find me a flight from JFK to SEA next Friday under $400, morning departure." },
      { role: 'tool_call', name: 'search_flights', args: { from: 'JFK', to: 'SEA', date: '2026-04-25', max_price: 400, time: 'morning' }, result: { count: 3, flights: [{ id: 'AS17', price: 348, dep: '07:55' }, { id: 'DL211', price: 392, dep: '09:10' }, { id: 'B6431', price: 401, dep: '08:30' }] }, status: 'ok' },
      { role: 'assistant', content: 'I found two morning options under $400: Alaska 17 at 7:55a ($348) and Delta 211 at 9:10a ($392). Which would you like?' },
      { role: 'user', content: 'Alaska, aisle seat please.' },
      { role: 'tool_call', name: 'reserve_seat', args: { flight: 'AS17', seat_pref: 'aisle' }, result: { seat: '14C', hold_id: 'h_9281' }, status: 'ok' },
      { role: 'tool_call', name: 'charge_card', args: { hold_id: 'h_9281', amount: 348 }, result: { error: 'card_declined', reason: 'insufficient_funds' }, status: 'error' },
      { role: 'assistant', content: 'Your card was declined. Want me to try a different payment method?' },
    ],
  },
  {
    id: 't_004',
    kind: 'summarizer',
    source: 'meeting-notes · 2026-04-20',
    title: 'Q2 planning sync - eng leads',
    verdict: null,
    tags: [],
    note: '',
    edited: false,
    source_doc: `Q2 PLANNING SYNC - Apr 18\n\nAttendees: Priya (PM), Marcus (Eng), Lin (Design), Tomas (Data)\n\nMarcus opened by flagging that the migration off the legacy queue is now blocking three downstream teams. Original ETA was end of Q1; current estimate is mid-May. Priya pushed back: the search team specifically committed roadmap items contingent on this. Marcus owned the slip and proposed pulling Anika in part-time from infra.\n\nLin walked through the new onboarding flow. The first-run coaching cards landed well in usability tests (5/6 participants completed without help) but the empty-state copy on the templates screen confused everyone. She'll iterate before code-complete on May 6.\n\nTomas raised that the experiment dashboard is showing inconsistent numbers across regions - likely a timezone bug introduced last week. He's deprioritizing the new metric work to fix this; expects 2 days.\n\nDecisions:\n- Anika joins the queue migration through end of May. Marcus to formalize w/ infra lead.\n- Onboarding ships May 6; Lin owns copy fixes.\n- Tomas pauses metric work, fixes regions bug first.\n\nOpen questions:\n- Do we need to renegotiate the search team's Q2 commitments? Priya to follow up offline.\n- Is the Anika loan blocking anything on infra's side?`,
    answer: `Q2 planning sync covered three main topics:\n\n1. **Queue migration is slipping** to mid-May (was end of Q1). Marcus is pulling Anika from infra part-time to help. This blocks three downstream teams including search.\n\n2. **Onboarding flow** tested well (5/6 success) but empty-state copy needs iteration. Ships May 6.\n\n3. **Experiment dashboard** has a timezone bug from last week. Tomas pausing other work for 2 days to fix.\n\nKey decisions: Anika joins migration through May, onboarding ships May 6, dashboard bug takes priority over new metrics.`,
  },
  {
    id: 't_005',
    kind: 'chat',
    source: 'support-chatbot · 2026-04-22',
    title: 'Login MFA loop',
    verdict: 'pass',
    tags: ['good-handoff'],
    note: 'Identified scope correctly, escalated cleanly.',
    edited: false,
    messages: [
      { role: 'user', content: "I keep getting asked for MFA over and over and never get in" },
      { role: 'assistant', content: "That sounds like a session loop. Quick check - are you on Safari, and have you cleared cookies for our domain in the last hour?" },
      { role: 'user', content: 'safari yes, cookies no' },
      { role: 'assistant', content: "Try clearing cookies for app.acme.com specifically and signing in fresh. If the loop persists, this is a known Safari ITP interaction we're tracking - I can open a ticket for engineering with your account ID." },
    ],
  },
  {
    id: 't_006',
    kind: 'rag',
    source: 'docs-qa · 2026-04-22',
    title: 'Webhook retry behavior',
    verdict: 'pass',
    tags: [],
    note: '',
    edited: false,
    query: 'How many times does the webhook retry on failure?',
    chunks: [
      { id: 'c1', score: 0.94, source: 'docs/webhooks/delivery.md#L8', used: true, text: 'Webhooks retry up to 5 times with exponential backoff (1m, 5m, 30m, 2h, 12h). After the fifth failure the event is marked dead and surfaced in the Events log.' },
    ],
    answer: 'Webhooks retry up to 5 times with exponential backoff at 1 minute, 5 minutes, 30 minutes, 2 hours, and 12 hours. After the fifth failure the event is marked dead.',
  },
  {
    id: 't_007',
    kind: 'agent',
    source: 'devops-agent · 2026-04-21',
    title: 'Roll back the bad deploy',
    verdict: 'fail',
    tags: ['unsafe-action', 'no-confirmation'],
    note: 'Agent ran rollback without listing what would change. Should have shown the diff first.',
    edited: true,
    messages: [
      { role: 'user', content: "the 14:02 deploy is bad, roll back" },
      { role: 'tool_call', name: 'rollback_deploy', args: { service: 'api', target: 'previous' }, result: { rolled_back_to: 'sha_a31f9c', affected_services: 7 }, status: 'ok' },
      { role: 'assistant', content: "Done. Rolled api back to a31f9c. 7 services were affected." },
    ],
  },
];

window.SAMPLE_TRACES = SAMPLE_TRACES;

// Tag taxonomy - recent + suggested + counts.
window.TAG_TAXONOMY = {
  recent: ['hallucinated-policy', 'ungrounded', 'wrong-tone', 'missing-step', 'unsafe-action'],
  suggested: [
    { tag: 'hallucinated-policy', count: 12 },
    { tag: 'ungrounded', count: 9 },
    { tag: 'wrong-tone', count: 7 },
    { tag: 'missing-step', count: 6 },
    { tag: 'unsafe-action', count: 5 },
    { tag: 'no-confirmation', count: 4 },
    { tag: 'over-apologetic', count: 3 },
    { tag: 'good-handoff', count: 3 },
    { tag: 'truncated', count: 2 },
    { tag: 'wrong-language', count: 1 },
    { tag: 'stale-info', count: 4 },
    { tag: 'misread-intent', count: 3 },
    { tag: 'wrong-tool', count: 2 },
    { tag: 'verbose', count: 2 },
  ],
};
